import 'reflect-metadata';
import { NestFactory } from '@nestjs/core';
import { ValidationPipe, Logger } from '@nestjs/common';
import { DocumentBuilder, SwaggerModule } from '@nestjs/swagger';
import { AppModule } from './app.module';
import { GlobalExceptionFilter } from './common/filters/global-exception.filter';

/**
 * Bootstrap notes tying back to frozen decisions:
 *
 *  - Global ValidationPipe with whitelist/forbidNonWhitelisted — Engineering
 *    Standards §6: unknown fields are rejected, not silently ignored.
 *  - GlobalExceptionFilter — every response follows the one error envelope
 *    (API Contract Design §1).
 *  - HTTPS for the staff channel is a Security Architecture §3 requirement
 *    (self-signed cert generated by the Host at first launch, trust
 *    established during Employee Invitation acceptance). That certificate
 *    provisioning is Host-owned bootstrap logic, wired in apps/host — this
 *    file accepts an already-prepared HTTPS context from the Host rather
 *    than generating certificates itself, keeping the API app portable
 *    (testable over plain HTTP in isolation) while the Host enforces the
 *    real deployment's transport security.
 *  - OpenAPI/Swagger generation — API Contract Design §1 ("REST +
 *    auto-generated OpenAPI"), giving any future third-party integration
 *    (or a partner SaaS conversion) a standard, language-agnostic contract
 *    for free from the same DTOs already required by Engineering Standards §6.
 */
async function bootstrap() {
  const app = await NestFactory.create(AppModule);
  const logger = new Logger('Bootstrap');

  app.setGlobalPrefix('api/v1'); // API Contract Design §1 — versioning convention

  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
    }),
  );

  app.useGlobalFilters(new GlobalExceptionFilter());

  const swaggerConfig = new DocumentBuilder()
    .setTitle('SmartTable API')
    .setDescription('Internal API contract — see API Contract Design for the full frozen specification.')
    .setVersion('1.0')
    .build();
  const document = SwaggerModule.createDocument(app, swaggerConfig);
  SwaggerModule.setup('api/v1/docs', app, document);

  const port = process.env.HTTP_PORT ?? 3000;
  await app.listen(port);
  logger.log(`SmartTable API listening on port ${port} (HTTPS termination handled by the Electron Host)`);
}

bootstrap();
